import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${inter.className} antialiased bg-gray-50 text-black dark:bg-gray-950 dark:text-white `}>
            <Navbar />
            {children}
            <Toaster position="top-center" reverseOrder={false} />
         </body>
      </html>
   );
}
